services:
  - type: web
    name: tkrcet-attendance-backend
    env: docker
    plan: free
    region: frankfurt
    numInstances: 1
    healthCheckPath: /api/status
    autoDeploy: true
    buildCommand: ''
    startCommand: ''
